### ISSUE TITLE
Warning from PV_array

### ISSUE THREAD

**Issue by willrogers** [DiamondLightSource/cothread#20]
﻿I'm getting a warning from PV_array: "Applying '+' to a non-numerical array is ill-defined. Returning a copy, but in the future this will error."

See https://github.com/numpy/numpy/blob/master/numpy/core/src/multiarray/number.c#L600

I think you are using a + as a shorthand for `numpy.copy()`; we could change that [here](https://github.com/dls-controls/cothread/blob/master/cothread/pv.py#L187), and we could also change another 4 places for consistency, or not, as you prefer.

**Comment by Araneidae** [comment]
Does look like an error.  I know where it's come from, and I'll highlight this to avoid confusion: the use of `+` as a special kind of copy is documented behaviour when applied to cothread augmented values, and is even documented (in `catools.rst`):

> In almost all circumstances an augmented value will behave exactly like a normal value, but there are a few rare cases where differences in behaviour are observed (these are mostly bugs). If this occurs the augmentation can be stripped from an augmented value value by writing `+value` – this returns the underlying value.

However, in the case you're highlighting we can see that all the values being treated are pure numpy array values, and so this use of `+` for copy is a mistake.

On a related note: I wonder if https://github.com/dls-controls/cothread/blob/7ab1f6ad4a4da5b1fc4bac777f176f1e006fcffe/cothread/dbr.py#L157 should be changed to `return self.copy()`?  I guess it's fine as it is, maybe `copy` would spring a surprise on us!

**Comment by T-Nicholls** [comment]
As of NumPy 1.25.0 using `+arr` in this way now raises a `_UFuncNoLoopError`

See: https://numpy.org/devdocs/release/1.25.0-notes.html#expired-deprecations

**Comment by AlexanderWells-diamond** [comment]
Do you happen to have the callstack for that exception?

**Comment by T-Nicholls** [comment]
Yep, here you go:
```
_______ GunBiasTest.test_bias_range_valid_returns_false_when_min_gt_max ________
Traceback (most recent call last):
  File "/home/jzs47954/git/old/topup/tests/fill/gun_bias_test.py", line 149, in setUp
    self.gb = GunBias(
  File "/home/jzs47954/git/old/topup/topup/fill/gun_bias.py", line 63, in __init__
    self._engine = PolynomialFit()
  File "/home/jzs47954/git/old/topup/topup/fill/bias_model.py", line 28, in __init__
    self.coeff_pvs = TopupPVArray(PolynomialFit.POLY_COEFF_PVS, get_on_create=True)
  File "/home/jzs47954/git/old/topup/topup/utils/pv_array.py", line 52, in __init__
    self._fetch()
  File "/home/jzs47954/git/old/topup/topup/utils/pv_array.py", line 65, in _fetch
    self._valid[i] = valid_pv_in_array(self.pv_array, i)
  File "/home/jzs47954/git/old/topup/topup/utils/pv_array.py", line 24, in valid_pv_in_array
    return pv_array.ok[index] and pv_array.severity[index] != AlarmSeverity.INVALID
  File "/scratch/jzs47954/pipenv/topup-17K3qhhA/lib/python3.9/site-packages/cothread/pv.py", line 187, in <lambda>
    ok        = property(lambda self: +self.__ok)
numpy.core._exceptions._UFuncNoLoopError: ufunc 'positive' did not contain a loop with signature matching types <class 'numpy.dtypes.BoolDType'> -> None
```
