### ISSUE TITLE
CI needs to support Python 3.6

### ISSUE THREAD

**Issue by Araneidae** [DiamondLightSource/cothread#44]
The standard Python on RHEL8 remains at version 3.6, so really this needs to be supported in CI!

**Comment by AlexanderWells-diamond** [comment]
I don't believe we can do this - the [python3-pip-skeleton](https://github.com/DiamondLightSource/python3-pip-skeleton) uses `pyproject.toml` for configuration, the current standard for recent versions of Python, and the support for that only arrives in `setuptools` versions from [~61](https://github.com/DiamondLightSource/python3-pip-skeleton). Unfortunately those versions of setuptools do not support Python 3.6 at all. 

While it doesn't really help us, Python 3.6 is two years past EOL, and so I don't see much gain in trying to retrofit the builds to work with Python 3.6.

**Comment by Araneidae** [comment]
Well, at least we do have (slight half baked) support for newer versions of Python on RHEL8.
