### ISSUE TITLE
Error installing cothread on Raspberry Pi 4 with Raspbian (buster)

### ISSUE THREAD

**Issue by Araneidae** [DiamondLightSource/cothread#65]
The following bug was reported when trying to install cothread:
![bug-report](https://github.com/DiamondLightSource/cothread/assets/4427635/ce5a5cbb-6e77-403c-9766-08a47386654b)

The relevant error message is:
```
pytoml.core.TomlError: /.../cothread/pyproject.toml(26, 8): expected_equals
```
which appears to point to the following line in https://github.com/DiamondLightSource/cothread/blob/82e277807c03c39bfe75de35609af7f8bf8cd9b6/pyproject.toml#L26

**Comment by Araneidae** [comment]
This may be an incompatibility with different versions of the pytoml library.  A google search suggest the following alternative syntax for the offending line:
```
license = {file = "LICENSE"}
```
which will be worth trying.

**Comment by AlexanderWells-diamond** [comment]
The package parsing the TOML file looks like it is "pytoml". This package was last released 5 years ago and is [marked deprecated](https://pypi.org/project/pytoml/) on PyPi. Is there no alternative library available for the user to try first? It feels like this is a problem on the parser's side, not ours...

**Comment by Araneidae** [comment]
Closing as no further communication from source of bug report and it looks like the underlying issue is solved.
